### ISSUE TITLE
Screenshots name not looks good, missing method name

### ISSUE THREAD

**Issue by rohandudam** [qxf2/qxf2-page-object-model#178]
Refer old build screenshot naming here :
https://circleci.com/gh/qxf2/qxf2-page-object-model/118#artifacts/containers/0
All screenshot holds method name while saving the image. So good to track.

Recent build:
https://circleci.com/gh/qxf2/qxf2-page-object-model/618
All images saved with the name "inner", missing "method name". Very hard to track or investigate.

**Comment by qxf2** [comment]
This is happening because we are not using @_screehshot as the first decorator.  The _screenshot decorator simply sets the name of its caller. I have added a comment in the decorator to note that it should be the first decorator of a method otherwise the name will be incorrect.

I also went ahead and made _screenshot the first decorator wherever it was called. There were 4 files and 13 instances using the _screenshot directory. Of that, only two files were using a decorator ahead of the _screenshot decorator. I have changed all instances in both files (page_objects/form_object.py and page_objects/table_object.py)

To the reviewer: I have changed three files:
a) page_objects/form_object.py: Made @_screenshot the first decorator in multiple places
b) page_objects/table_object.py: Made @_screenshot the first decorator in multiple places
c) utils/Wrapit.py: Added a comment in the screenshot method to note the usage. It will help the next person that debugs a similar issue.

I ran the four web GUI tests again and I was able to see the screenshot names set correctly. To test, you can run `pytest` and then examine the `screenshots` directory for the tests and see if the name of the method is set correctly. I am attaching an example screenshot of GOOD_ behaviour.


![GOOD_178_fix](https://user-images.githubusercontent.com/4759449/71769360-331d5d00-2f46-11ea-84a6-f31119c0097f.png)

**Comment by qxf2** [comment]
PR has been raised here: https://github.com/qxf2/qxf2-page-object-model/pull/179

**Comment by qxf2** [comment]
I am closing this issue since it has been fixed in #179
