### ISSUE TITLE
'Maintainer' in Docker file has been deprecated

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#219]
Codacy complains that 'Maintainer' in Dockerfile has been deprecated. Can the person working on this ticket please check what it should be replaced with? Please remember to test the dockerfile after the change since this is a very popular feature we support.

https://app.codacy.com/manual/qxf2/qxf2-page-object-model/issues?bid=16560353&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJFcnJvciJdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6W119LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltdfV0=

**Comment by akkuldn** [comment]
This issue is caused as the maintainer instruction is deprecated.
According to the Dockerfile reference, 'MAINTAINER' has been deprecated in favor of using the 'LABEL' instruction: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated.
Hereby changed the dockerfile code from Maintainer Qxf2 Services to LABEL maintainer = "Qxf2 Services"
