### ISSUE TITLE
Make Dockerfile use wget or curl consistently

### ISSUE THREAD

**Issue by qxf2** [qxf2/qxf2-page-object-model#221]
Codacy is complaining about our inconsistent use of curl and wget within the dockerfile. Please fix this:

https://app.codacy.com/manual/qxf2/qxf2-page-object-model/issues?bid=16560353&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJXYXJuaW5nIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjMwNTMiXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W119XQ==

To the person fixing this issue: Please make sure to test your dockerfile well. It is one of the most used features in our framework.

**Comment by akkuldn** [comment]
This issue is caused as the maintainer instruction is deprecated.
According to the Dockerfile reference, 'MAINTAINER' has been deprecated in favor of using the 'LABEL' instruction: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated.
Hereby changed the dockerfile code from Maintainer Qxf2 Services to LABEL maintainer = "Qxf2 Services"

**Comment by akkuldn** [comment]
We are facing this issue as we are using two tools that has the same effects.

**Comment by akkuldn** [comment]
The issue was resolved by :
1. Changing all the curl commands in the docker file with equivalent get commands
2. Building the docker image from the updated docker file
3. Running a test to fetch the title of a webpage from inside the docker container to verify if it's working fine
